networks:
  internal:
    external: true
    name: football-network
volumes:
  football-gto-staticfiles:
    external: true
    name: football-gto-staticfiles
# Общее для всех контейнеров - указываем сеть internal, env_file: .env и правила для логирования
x-container:
  &base-container
  networks:
    - internal
  env_file:
    - .env
  logging:
    options:
      max-size: "5m"
      max-file: "2"
services:
  api:
    <<: *base-container
    image: gto-api:1.0.0-python3.14.7-slim-trixie
    build:
      context: ./api
      dockerfile: ../docker/python/Dockerfile
      args:
        LOCAL_USER_ID_ARG: ${LOCAL_USER_ID}
        LOCAL_GROUP_ID_ARG: ${LOCAL_GROUP_ID}
    command:
      [
        "uvicorn",
        "app.main:main_app",
        "--host", "0.0.0.0",
        "--port", "8000",
        "--proxy-headers",
        "--forwarded-allow-ips=*"
      ]
  web:
    <<: *base-container
    image: gto-web:1.0.0-python3.14.7-slim-trixie
    build:
      context: ./web
      dockerfile: ../docker/python/Dockerfile
      args:
        LOCAL_USER_ID_ARG: ${LOCAL_USER_ID}
        LOCAL_GROUP_ID_ARG: ${LOCAL_GROUP_ID}
    volumes:
      - football-gto-staticfiles:/app/staticfiles
    command:
      ["python", "manage.py", "runserver", "0.0.0.0:8000"]
